---
# tasks file for Web_Servers

    - name: install apache and php for Ubuntu Servers
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
