---
# tasks file for Web_Servers

    - name: install apache and php for Ubuntu Servers
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php for CentOS Servers
      tags: apache,centos,httpd
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"

    - name: start httpd (CentOS)
      tags: apache, centos, httpd
      service:
        name: httpd
        stage: started
      when: ansible_distribution == "CentOS"